# Generated by Django 3.2.3 on 2021-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RutUsuario', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Rut del Usuario')),
                ('nombreCom', models.CharField(max_length=50, verbose_name='Nombre completo del usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono del usuario')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.CharField(max_length=70, verbose_name='Mail')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
            ],
        ),
    ]
