# Generated by Django 3.2.3 on 2021-07-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='RutUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Telefono del usuario'),
        ),
    ]
